# Generated by Django 5.0.6 on 2024-06-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='product/image'),
        ),
    ]
