# Generated by Django 5.0.6 on 2024-06-19 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_accounts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='category',
        ),
        migrations.AddField(
            model_name='accounts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.category'),
        ),
    ]
