# Generated by Django 5.0.6 on 2024-06-23 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_accounts_category_accounts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
