# Generated by Django 5.0.7 on 2024-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
