# Generated by Django 5.0.6 on 2024-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
