# Generated by Django 5.0.6 on 2024-06-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_product_name_products_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='discount',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='men', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='expire_date',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
