# Generated by Django 5.0.6 on 2024-06-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_products_category_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='expire_date',
        ),
    ]
