# Generated by Django 5.0.6 on 2024-07-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
