# Generated by Django 5.0.7 on 2024-08-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_admanagement_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='admanagement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/'),
        ),
    ]
